### ISSUE TITLE
Create an address schema

### ISSUE THREAD

**Issue by randallmorey** [randallmorey/ceevee#13]
Write a [mongoose schema](http://mongoosejs.com/docs/guide.html) for a standard physical _address_ in `app/schemas/address.js`.  It should contain the following fields:

- **`street_address`**:  `string`
- **`extended_address`**:  `string`
- **`locality`**:  `string`
- **`region`**:  `string`
- **`postal_code`**:  `string`
- **`country_name`**:  `string`

No default values, additional validations, or plugins are required.  Since schemas are declarative, no tests are required.

This schema is loosely based on [h-adr](http://microformats.org/wiki/h-adr)

**Comment by randallmorey** [comment]
Does not exist yet.

**Comment by randallmorey** [comment]
@BeatrizElena I realized it's probably better if none of the fields are required.  In the case of Job or Bio, a user may just want to enter country/region, rather than a full address.  I think it makes sense to leave all fields optional, and users will provide as much or as little detail as they want.

**Comment by BeatrizElena** [comment]
Okay Randy. I expect to work on this and hopefully be done tomorrow evening. It looks like something I can handle.

**Comment by BeatrizElena** [comment]
@randallmorey When committing address.js, I get a  "parsing error: unexpected token postal_code" and a code: elifecycle. Any guidance on how to troubleshoot it?

**Comment by randallmorey** [comment]
Can you paste the whole output?

- Randall Morey

**Comment by BeatrizElena** [comment]
*Terminal command and output:*

ceevee beatriz$ npm run commit


> ceevee@0.0.0 commit /Users/beatriz/code/ceevee

> npm run test:local && git-cz



> ceevee@0.0.0 test:local /Users/beatriz/code/ceevee

> docker-compose run test


Starting ceevee_mongodb_1 ... done


> ceevee@0.0.0 test /src

> npm run lint && NODE_ENV=test nyc mocha --require babel-core/register
test/unit/**/*.js test/integration/**/*.js test/acceptance/**/*.js



> ceevee@0.0.0 lint /src

> eslint config/**/*.js app/**/*.js test/**/*.js



/src/app/schemas/address.js

  19:3  error  Parsing error: Unexpected token postal_code


*✖ 1 problem (1 error, 0 warnings)*


npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! ceevee@0.0.0 lint: `eslint config/**/*.js app/**/*.js test/**/*.js`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the ceevee@0.0.0 lint script.

npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.


npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2018-04-01T02_38_15_905Z-debug.log

npm ERR! Test failed.  See above for more details.

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! ceevee@0.0.0 test:local: `docker-compose run test`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the ceevee@0.0.0 test:local script.

npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.


npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/beatriz/.npm/_logs/2018-04-01T02_38_16_654Z-debug.log

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! ceevee@0.0.0 commit: `npm run test:local && git-cz`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the ceevee@0.0.0 commit script.

npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.


npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/beatriz/.npm/_logs/2018-04-01T02_38_16_702Z-debug.log



*debug.log content:*
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run',
'commit' ]
2 info using npm@5.8.0
3 info using node@v8.10.0
4 verbose run-script [ 'precommit', 'commit', 'postcommit' ]
5 info lifecycle ceevee@0.0.0~precommit: ceevee@0.0.0
6 info lifecycle ceevee@0.0.0~commit: ceevee@0.0.0
7 verbose lifecycle ceevee@0.0.0~commit: unsafe-perm in lifecycle true
8 verbose lifecycle ceevee@0.0.0~commit: PATH:
/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/beatriz/code/ceevee/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle ceevee@0.0.0~commit: CWD: /Users/beatriz/code/ceevee
10 silly lifecycle ceevee@0.0.0~commit: Args: [ '-c', 'npm run test:local
&& git-cz' ]
11 silly lifecycle ceevee@0.0.0~commit: Returned: code: 1  signal: null
12 info lifecycle ceevee@0.0.0~commit: Failed to exec commit script
13 verbose stack Error: ceevee@0.0.0 commit: `npm run test:local && git-cz`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous>
(/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous>
(/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:209:5)
14 verbose pkgid ceevee@0.0.0
15 verbose cwd /Users/beatriz/code/ceevee
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "commit"
18 verbose node v8.10.0
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error ceevee@0.0.0 commit: `npm run test:local && git-cz`
22 error Exit status 1
23 error Failed at the ceevee@0.0.0 commit script.
23 error This is probably not a problem with npm. There is likely
additional logging output above.
24 verbose exit [ 1, true ]

**Comment by randallmorey** [comment]
What’s the contents of that JS file?  There error is from the linter. Might be a syntax error. 

- Randall Morey

**Comment by randallmorey** [comment]
...I'm guessing a missing comma

**Comment by BeatrizElena** [comment]
I did have a syntax error that I fixed, a missing comma before postal_code.
Still failing test though.

Here’s the new terminal output:

ceevee beatriz$ npm run commit

> ceevee@0.0.0 commit /Users/beatriz/code/ceevee
> npm run test:local && git-cz


> ceevee@0.0.0 test:local /Users/beatriz/code/ceevee
> docker-compose run test

Starting ceevee_mongodb_1 ... done

> ceevee@0.0.0 test /src
> npm run lint && NODE_ENV=test nyc mocha --require babel-core/register
test/unit/**/*.js test/integration/**/*.js test/acceptance/**/*.js


> ceevee@0.0.0 lint /src
> eslint config/**/*.js app/**/*.js test/**/*.js

module.js:545
    throw err;
    ^

Error: Cannot find module 'mongoose-timestamp'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/app/schemas/user.js:1:2356)
    at Module._compile (module.js:649:30)
    at Module.replacementCompile
(/src/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at loader (/src/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function)
(/src/node_modules/babel-register/lib/node.js:154:7)
    at Object.<anonymous>
(/src/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/app/models/user.js:1:15418)
    at Module._compile (module.js:649:30)
    at Module.replacementCompile
(/src/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at loader (/src/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function)
(/src/node_modules/babel-register/lib/node.js:154:7)
    at Object.<anonymous>
(/src/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/test/unit/emails/password-reset.js:5:1)
    at Module._compile (module.js:649:30)
    at Module.replacementCompile
(/src/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at loader (/src/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function)
(/src/node_modules/babel-register/lib/node.js:154:7)
    at Object.<anonymous>
(/src/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at /src/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/src/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/src/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/src/node_modules/mocha/bin/_mocha:582:18)
    at Module._compile (module.js:649:30)
    at Module.replacementCompile
(/src/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports
(/src/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous>
(/src/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at runMain (/root/.node-spawn-wrap-34-4b17f72c4c0e/node:68:10)
    at Function.<anonymous>
(/root/.node-spawn-wrap-34-4b17f72c4c0e/node:171:5)
    at Object.<anonymous> (/src/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at /root/.node-spawn-wrap-34-4b17f72c4c0e/node:178:8
    at Object.<anonymous>
(/root/.node-spawn-wrap-34-4b17f72c4c0e/node:181:3)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
ERROR: Coverage for lines (9.09%) does not meet global threshold (100%)
ERROR: Coverage for functions (0%) does not meet global threshold (100%)
ERROR: Coverage for branches (0%) does not meet global threshold (100%)
ERROR: Coverage for statements (8.7%) does not meet global threshold (100%)
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
*All files* |*      8.7* |*        0* |*        0* |*     9.09* |
      |
* models  * |*     6.78* |*        0* |*        0* |*     7.14* |
      |
*  user.js* |*     6.78* |*        0* |*        0* |*     7.14* |*...
242,247,248* |
* schemas * |*       20* |*      100* |*        0* |*       20* |
      |
*  user.js* |*       20* |*      100* |*        0* |*       20* |*...
29,30,31,34* |
----------|----------|----------|----------|----------|----------------|

=============================== Coverage summary
===============================
*Statements   : 8.7% ( 6/69 )*
*Branches     : 0% ( 0/20 )*
*Functions    : 0% ( 0/2 )*
*Lines        : 9.09% ( 6/66 )*
================================================================================
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ceevee@0.0.0 test:local: `docker-compose run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ceevee@0.0.0 test:local script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beatriz/.npm/_logs/2018-04-01T13_39_13_651Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ceevee@0.0.0 commit: `npm run test:local && git-cz`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ceevee@0.0.0 commit script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beatriz/.npm/_logs/2018-04-01T13_39_13_690Z-debug.log

**Comment by randallmorey** [comment]
It says it can’t find a module.  Try running the npm install command.

**Comment by BeatrizElena** [comment]
I went back and re-read the README and did the one-time setup. It looks like everything works now, does it?

**Comment by randallmorey** [comment]
Did you push anything?

**Comment by BeatrizElena** [comment]
Do I have to do a pull request first? Or just git push?

**Comment by randallmorey** [comment]
Push first.

**Comment by BeatrizElena** [comment]
This closes issue #13.
