### ISSUE TITLE
Create a personal model

### ISSUE THREAD

**Issue by randallmorey** [randallmorey/ceevee#14]
Build a mongoose schema & model for `personal`, or information about the subject of the resume.  Only the `name` field is required.

- **`user`**:  `user` (relationship) _required_ the user that owns this bio
- **`name`**:  `string` _required_ full name to show in resume
- **`title`**:  `string` job title to show in resume
- **`description`**:  `string` optional descriptive text about the resume owner
- **`location`**:  `address` (nested schema) location to show in resume
- **`email`**:  `string`
- **`voice`**:  `string` e.g. old-fashioned telephone number
- **`url`**:  `string`  e.g. to personal website or profile
- **`linked_in_username`**:  `string`
- **`facebook_username`**:  `string`
- **`twitter_username`**:  `string`
- **`github_username`**:  `string`

Validations for email, voice, and URL should work intuitively.  Validations for social media usernames should verify that the string **is not** a URL, as some users may attempt to paste a full URL.

Include unit and integration tests as appropriate.

This issue depends on #13

**Comment by BeatrizElena** [comment]
Created schema. Researching the difference between a schema and a model so I can create model next.

**Comment by randallmorey** [comment]
Address does not require a model. I think it’s ready for a pull request. Be sure to use the issue closing syntax in your PR message, see end of readme. 

- Randall Morey
