### ISSUE TITLE
Create an organization model

### ISSUE THREAD

**Issue by randallmorey** [randallmorey/ceevee#15]
Build a mongoose schema & model for `organization`.  Only the `name` field is required.

- **`user`**:  `user` (relationship) _required_ the user that owns this instance
- **`name`**:  `string` _required_ full name of org to show in resume
- **`location`**:  `address` (nested schema) location to show in resume
- **`url`**:  `string`  e.g. to org website

Validate URL.

Include unit and integration tests as appropriate.

This issue depends on #13

**Comment by sonumeewa** [comment]
I would like to work on it.
