### ISSUE TITLE
Create an education model

### ISSUE THREAD

**Issue by randallmorey** [randallmorey/ceevee#19]
Build a mongoose schema & model for `education`.

- **`user`**:  `user`. _required_ the user that owns this instance
- **`name`**:  `string` _required_ area of study, major, etc
- **`credential`**:  `string` _required_ earned credential (e.g. "Bachelors of Science", "Masters of Arts ", "PhD, English", "certificate", etc.)
- **`organization`**:  `organization` (relationship) _required_ institution
- **`completed_on`**:  `date` optional date completed
- **`description`**:  `string` optional description of this instance

Include unit and integration tests as appropriate.

This issue depends on #15

**Comment by randallmorey** [comment]
@BeatrizElena any thoughts on the fields for education?  Is anything missing that should appear on a resume?

**Comment by BeatrizElena** [comment]
@randallmorey are you thinking of credential answers as a dropdown menu? There are seminars or online courses that may have a certificate of attendance at the most so I think the app should allow for flexibility on how people handle this question.

**Comment by randallmorey** [comment]
At the model level it would be open ended. Not sure about the UI yet. 

- Randall Morey
